name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no registry
        if: ${{ secrets.CI_REGISTRY_USER != '' && secrets.CI_REGISTRY_PASSWORD != '' && secrets.CI_REGISTRY != '' }}
        run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.CI_REGISTRY_USER }}" --password-stdin "${{ secrets.CI_REGISTRY }}"

      - name: Simular build
        run: echo "simulando um docker build"